name: Java CI with Maven and TestNG

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Start Xvfb
        run: |
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with Maven
        run: mvn -B test -DsuiteXmlFile=testng.xml

      - name: Archive TestNG HTML reports
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: testng-html-reports
          path: target/surefire-reports/emailable-report.html